### ISSUE TITLE
LookupError: No gradient defined for operation 'ENet/bottleneck2_0_main_max_pool' (op type: MaxPoolWithArgmax)

### ISSUE THREAD

**Issue by zhangxgu** [kwotsin/TensorFlow-ENet#1]
When I run ./train.sh, I find this error. Is this because of the Tensorflow version or I need to define the gradient of **ENet/bottleneck2_0_main_max_pool** myself?
Thx!

**Comment by kwotsin** [comment]
Are you using a TF version lesser than r1.2? In r1.1 and below the gradient for this argmax isn't defined but this was fixed in r1.2.

**Comment by zhangxgu** [comment]
@kwotsin  Thx! I did not update TF for a long time ....Let me see it .
