### ISSUE TITLE
In the first step, acc and iou are all zero ? What's the reason about this?

### ISSUE THREAD

**Issue by dreambear1234** [kwotsin/TensorFlow-ENet#10]
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Global Step 174376: Streaming Accuracy: 0.0000     Streaming Mean IOU: 0.0000     Per-class Accuracy: 0.0000 (1.27 sec/step)
INFO:tensorflow:Global Step 174377: Streaming Accuracy: 0.9499     Streaming Mean IOU: 0.9000     Per-class Accuracy: 0.9493 (0.12 sec/step)
INFO:tensorflow:Global Step 174378: Streaming Accuracy: 0.9491     Streaming Mean IOU: 0.8970     Per-class Accuracy: 0.9484 (0.12 sec/step)
INFO:tensorflow:Global Step 174379: Streaming Accuracy: 0.9517     Streaming Mean IOU: 0.8997     Per-class Accuracy: 0.9507 (0.12 sec/step)
INFO:tensorflow:Global Step 174380: Streaming Accuracy: 0.9456     Streaming Mean IOU: 0.8844     Per-class Accuracy: 0.9456 (0.12 sec/step)

**Comment by kwotsin** [comment]
@dreambear1234 That is due to how the code computes the accuracy before there is any actual evaluation being done, so the accuracy defaults to zero.
