### ISSUE TITLE
Multiple initial blocks have no effect

### ISSUE THREAD

**Issue by lucaslie** [kwotsin/TensorFlow-ENet#15]
It seems like having multiple initial blocks won't change the network architecture since you always pass `inputs`  to `initial_block()`. I guess it's supposed to be something like: 
```
#=================INITIAL BLOCK=================
net = inputs
for i in xrange(1, max(num_initial_blocks, 1) + 1):
    net = initial_block(net, scope='initial_block_' + str(i))
```

https://github.com/kwotsin/TensorFlow-ENet/blob/6a53f7f7f9e1b5f413d9d83c06b20aa240e333d7/enet.py#L425

**Comment by kwotsin** [comment]
Thanks for bringing this up. I think you are right, although the net cannot be directly assigned as the inputs. We will have to at least call the initial_block at least once before we call the successive ones (see new changes).
