### ISSUE TITLE
performance issue about inference (0.5~1 fps)

### ISSUE THREAD

**Issue by DellBrother** [kwotsin/TensorFlow-ENet#19]
hi, Kwotsin
Thank you so much for the implementation! I trained the model with my data and got much better mIOU comparing to legacy method. 

However, the inference performance is not good as the stats from the paper. My result is about 0.5~1 fps for 1280x720 image, on GeForce GTX 1080.  My class number is 2 so it might save much MIPS. I run the inference with OpenCV real-time images.

Any idea about the root cause?

thanks a lot,
BRS, Dell

**Comment by DellBrother** [comment]
Sorry, I just measured the ENet inference timing. it is about 80ms-90ms for 1 frame. Might need more optimization also. 

Thanks,
BRS, Dell

**Comment by msson** [comment]
@DellBrother Hi, how did you check the enet inference timing exactly? I also see 0.5~1 fps for 1024x768 image. Thanks.

**Comment by xiaoerlaigeid** [comment]
@DellBrother  How did optimized ENet ? Could tell me how  to reducing the inference time ?
