### ISSUE TITLE
Why is `is_training` set `Ture` in `test.py`

### ISSUE THREAD

**Issue by changlinzhang** [kwotsin/TensorFlow-ENet#22]
Hi Kwotsin, thanks a lot for your work.
But why is `is_training` set `Ture` in `test.py`?

**Comment by kwotsin** [comment]
This was made as the model performed better when this setting was used, maintaining the train-test split. This issue was referenced quite a few times in the TF repo here https://github.com/tensorflow/models/issues/391, where you can refer to for more informatino.
