### ISSUE TITLE
Problem occurred~

### ISSUE THREAD

**Issue by pandamax** [kwotsin/TensorFlow-ENet#7]
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxPoolWithArgmax' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'; Targmax in [DT_INT64]; T in [DT_DOUBLE]
  device='GPU'; Targmax in [DT_INT64]; T in [DT_FLOAT]
  device='GPU'; Targmax in [DT_INT64]; T in [DT_HALF]

	 [[Node: ENet_1/bottleneck1_0_main_max_pool = MaxPoolWithArgmax[T=DT_FLOAT, Targmax=DT_INT64, ksize=[1, 2, 2, 1], padding="SAME", strides=[1, 2, 2, 1]](ENet_1/initial_block_1_concat)]]

**Comment by pandamax** [comment]
python2.7 tensorflow_gpu 1.2

**Comment by kwotsin** [comment]
Which system are you running on and did you build TF from source? This seems to be a similar problem encountered in older versions of TF where `MaxPoolWithArgmax` and some other ops were not yet implemented. Please also try running with TF 1.3 to see if the problem persists.

**Comment by chandrakantkhandelwal** [comment]
I have used the code for training on some customised data and I was able to run it sucessfully with tensroflow-gpu 1.2 (code doosn't runs on CPU verison of tensorflow 1.2, as there are some ops not supported on CPU).

**Comment by kwotsin** [comment]
It seems like TF-CPU v1.2 does not have some ops supported, rather than it being an issue with the code. I suggest you to raise an issue on TF to verify this issue. I'll close this issue for now.

**Comment by gunshi** [comment]
H @kwotsin , I also get the same error:

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxPoolWithArgmax' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>


However I'm running it with tensorflow 1.4(gpu support), on a machine with 2 gpus. From the message, it looks like the gpu device isn't getting registered, and there's no explicit statement like 'with device('/gpu/:0')' in the predict_segmentation.py code, how can I change it to correct this?
Thanks!
