### ISSUE TITLE
Wrong input to calculate the weights.

### ISSUE THREAD

**Issue by zhaotiny** [kwotsin/TensorFlow-ENet#9]
when calculating the weights using "def ENet_weighing(image_files=image_files, num_classes=12)", you feed imge_files as input. But according to my understanding, we should feed annotation_files as input since we calculate the weights based on the frequencies of each class. Am I correct?

**Comment by kwotsin** [comment]
@zhaotiny I believe the code is using the annotation files as the input, not the raw images? See the code here again:

https://github.com/kwotsin/TensorFlow-ENet/blob/master/get_class_weights.py

the images come from trainannot, which is the annotation files.
